<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Créer Projet</title>
</head>
<body>
    <form method="post" action="?route=checkCreateProject">
        <label for="title">Title</label>
        <input type="text" name="title"/>
        <label for="content">Content</label>
        <input type="text" name="content"/>
        <label for="user_id">User Id</label>
        <input type="text" name="user_id" value="NULL"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>