<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
    <nav>
        <ul>
            <li><a href="?route=listUsers">Utilisateurs</a></li>
            <li><a href="?route=listProjects">Projets</a></li>
            <li><a href="?route=listMedias">Médias</a></li>
            <li><a href="?route=listServices">Services</a></li>
            <li><a href="?route=listForms">Questionnaires</a></li>
            <li><a href="?route=listQuestions">Questions</a></li>
        </ul>
    </nav>
    <?php
        require "templates/admin/_admin/$template.phtml"
    ?>
</body>
</html>