<?php
    $item = $data["question"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $item -> getContent() ?></title>
</head>
<body>
    <h3><?= $item -> getFormId() ?></h3>
    <?= $item -> getContent() ?>
    <button><a href="?route=updateQuestion&question_id=<?= $item -> getId() ?>">Modifier</a></button>
    <button><a href="?route=deleteQuestion&question_id=<?= $item -> getId() ?>">Supprimer</a></button>
</body>
</html>