<?php
    $user_id = $data["user_id"];
    $forms = $data["forms"];
    $projects = $data["projects"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accueil Client</title>
</head>
<body>
    <h1>Bienvenue chez vous..!</h1>
    <?php if($forms != null) { ?>
        <?php foreach ($forms as $form) { ?>
            <p>Le questionnaire "<?= $form -> getTitle() ?>" n'attends que vous..!</p>
            <button><a href="?route=formHomeClient&form_id=<?= $form -> getId() ?>">Remplir "<?= $form -> getTitle() ?>"</a></button>
        <?php } ?>
    <?php } else { ?>
        <p>Aucun questionnaire en attente</p>
    <?php } ?>
    <?php if($projects != null) { ?>
        <?php foreach ($projects as $project) { ?>
            <p>Vous allez enfin pouvoir découvrir <a href="?route=projectClient&project_id=<?= $project -> getId() ?>">votre projet..!</a> C'est excitant..!</p>
            <button><a href="?route=projectClient&project_id=<?= $project -> getId() ?>">Voir "<?= $project -> getTitle() ?>"</a></button>
        <?php } ?>
    <?php } else { ?>
        <p>Aucun projet en attente</p>
    <?php } ?>
    <br/>
    <br/>
    <button><a href="?route=agendaClient">Prendre rendez-vous</a></button>
</body>
</html>