<?php
    $item = $data["rendezVous"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $item -> getDate() -> format("Y-m-d H:i:s") ?></title>
</head>
<body>
    <h1><?= $item -> getDate() -> format("Y-m-d H:i:s") ?></h1>
    <h2><?= $item -> getMotif() ?></h2>
    <p><?= $user -> getFirstName() ?> <?= $user -> getLastName() ?></p>
    <p><?= $user -> getEmail() ?></p>
    <p><?= $item -> getId() ?></p>
    <button><a href="?route=updateRendezVous&rendezVous_id=<?= $item -> getId() ?>">Modifier</a></button>
    <button><a href="?route=deleteRendezVous&rendezVous_id=<?= $item -> getId() ?>">Supprimer</a></button>
</body>
</html>