<?php
    $item = $data["rendezVous"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Modifier utilisateur</title>
</head>
<body>
    <form method="post" action="?route=checkUpdateRendezVous&rendezVous_id=<?= $item -> getId() ?>">
        <label for="date">Date</label>
        <input type="date" name="date" value="<?= $item -> getDate()->format('Y-m-d')?>" />
        <label for="time">Time</label>
        <input type="time" name="time" value="<?= $item -> getDate()->format('H:i')?>"/>
        <label for="role">Motif</label>
        <select name="motif" value="<?= $item -> getMotif()?>">
            <option value="découverte">Appel de découverte (30 minutes)</option>
            <option value="suivi">Suivi de projet (60 minutes)</option>
            <option value="présentation">Présentation de projet (90 minutes)</option>
        </select>
        <label for="user_id">User Id</label>
        <input type="text" name="user_id" value="<?= $item -> getUserId() ?>" />
        <input type="submit" value="Submit"/>
    </form>
    <?php if($_SESSION["error"]){ ?>
        <p><?= $_SESSION["error"] ?></p>
    <?php } ?>
</body>
</html>