<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Auth User</title>
</head>
<body>
    <form method="post" action="?route=checkAuthUser">
        <?php if($data["email"]) { ?>
            <label for="email">Email</label>
            <input type="email" name="email" value="<?= $_SESSION["email"] ?>"/>
        <?php } else { ?>
            <label for="email">Email</label>
            <input type="email" name="email" placeholder="vous@email.fr"/>
        <?php } ?>
        <label for="password">Password</label>
        <input type="password" name="password" required/>
        <input type="submit" value="Se connecter"/>
    </form>
    <?php if($data["error"]){ ?>
        <p><?= $data["error"] ?></p>
    <?php } ?>

</body>
</html>
