<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste Questionnaires</title>
</head>
<body>
    <h1>Questionnaires</h1>
    <button><a href="?route=createForm">Créer un questionnaire</a></button>
    <ul>
        <?php foreach($data as $item){ ?>
            <li>
                <p><?= $item -> getTitle() ?></p>
                <p><?= $item -> getId() ?></p>
                <button><a href="?route=showForm&form_id=<?= $item -> getId() ?>">Plus d'infos</a></button>
                <button><a href="?route=updateForm&form_id=<?= $item -> getId() ?>">Modifier</a></button>
                <button><a href="?route=deleteForm&form_id=<?= $item -> getId() ?>">Supprimer</a></button>
            </li>
        <?php } ?>
    </ul>
</body>
</html>