<?php
    $item = $data["user"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accueil Client</title>
</head>
<body>
    <h1>Bienvenue chez vous..!</h1>
    <p><?= $item -> getEmail() ?></p>
</body>
</html>