<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Prendre Rendez-vous</title>
</head>
<body>
    <h1>Rendez-vous</h1>
    <button><a href="?route=homeClient">Retour</a></button>
</body>
</html>