<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste Services</title>
</head>
<body>
    <h1>Services</h1>
    <button><a href="?route=createService">Créer un Service</a></button>
    <ul>
        <?php foreach($data as $item){ ?>
            <li>
                <p><?= $item -> getTitle() ?></p>
                <p><?= $item -> getId() ?></p>
                <button><a href="?route=showService&service_id=<?= $item -> getId() ?>">Plus d'infos</a></button>
                <button><a href="?route=updateService&service_id=<?= $item -> getId() ?>">Modifier</a></button>
                <button><a href="?route=deleteService&service_id=<?= $item -> getId() ?>">Supprimer</a></button>
            </li>
        <?php } ?>
    </ul>
</body>
</html>