<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Créer utilisateur</title>
</head>
<body>
    <form method="post" action="?route=checkCreateUser">
        <label for="email">Email</label>
        <input type="email" name="email"/>
        <label for="password">Password</label>
        <input type="password" name="password"/>
        <label for="role">Role</label>
        <select name="role">
            <option value="client">CLIENT</option>
            <option value="admin">ADMIN</option>
        </select>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>