<?php
    $item = $data["user"];
    var_dump($_SESSION["error"]);
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Modifier utilisateur</title>
</head>
<body>
    <form method="post" action="?route=checkUpdateUser&user_id=<?= $item -> getId() ?>">
        <label for="first_name">Prénom</label>
        <input type="text" name="first_name" value="<?= $item -> getFirstName() ?>"/>
        <label for="last_name">Nom de Famille</label>
        <input type="text" name="last_name" value="<?= $item -> getLastName() ?>"/>
        <label for="email">Email</label>
        <input type="email" name="email" value="<?= $item -> getEmail() ?>"/>
        <label for="role">Role</label>
        <select name="role">
            <option value="client">CLIENT</option>
            <option value="admin">ADMIN</option>
        </select>
        <label for="created_at">Created At</label>
        <input type="text" name="created_at" value="<?= $item -> getCreatedAt() -> format("Y-m-d H:i:s") ?>"/>
        <input type="submit" value="Submit"/>
    </form>
    <form method="post" action="?route=checkUpdateUser&user_id=<?= $item -> getId() ?>">
        <label for="password">Password</label>
        <input type="password" name="password" required/>
        <label for="checkPassword">Check Password</label>
        <input type="password" name="checkPassword" required/>
        <input type="submit" value="Submit"/>
    </form>
    <?php if($_SESSION["error"]){ ?>
        <p><?= $_SESSION["error"] ?></p>
    <?php } ?>
</body>
</html>