<?php
    $form = $data["form"];
    $questions = $data["questions"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $form -> getTitle() ?></title>
</head>
<body>
    <form method="post" action="?route=sendFormClient">
        <?php $i=1; foreach ($questions as $question) { ?>
            <label for="question_<?= $i ?>"><?= $i ?> <?= $question -> getContent() ?></label>
            <br/>
            <input type="textarea" name="question_<?= $i ?>">
            <br/>
            <?php $i++ ?>
        <?php } ?>
        <input type="submit" value="Envoyer" />
    </form>
</body>
</html>