<?php
    $form = $data["form"];
    $questions = $data["questions"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $form -> getTitle() ?></title>
</head>
<body>
    <form method="get" action="?route=sendFormClient">
        <input type="submit" value="Envoyer" />
    </form>
</body>
</html>