<?php
    $item = $data["form"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $item -> getTitle() ?></title>
</head>
<body>
    <h1><?= $item -> getTitle() ?></h1>
    <p><?= $item -> getContent() ?></p>
    <button><a href="?route=formClient&form_id=<?= $item -> getId() ?>">Commencer votre questionnaire</a></button>
    <br/>
    <button><a href="?route=homeClient">Retour à votre espace client</a></button>
</body>
</html>