<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Créer média</title>
</head>
<body>
    <form method="post" action="?route=checkCreateMedia">
        <label for="alt">Alt</label>
        <input type="text" name="alt"/>
        <label for="url">Url</label>
        <input type="text" name="url"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>