<?php
    $item = $data["media"];
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, media-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $item -> getAlt() ?></title>
</head>
<body>
    <h1><?= $item -> getAlt() ?></h1>
    <p><?= $item -> getId() ?></p>
    <p><?= $item -> getUrl() ?></p>
    <button><a href="?route=updateMedia&media_id=<?= $item -> getId() ?>">Modifier</a></button>
    <button><a href="?route=deleteMedia&media_id=<?= $item -> getId() ?>">Supprimer</a></button>
</body>
</html>